### ISSUE TITLE
GCW Connect crashing on launch on May 21 2020 build of OpenDingUX on RG350M

### ISSUE THREAD

**Issue by jboulter11** [hanskokx/gcwconnect#6]
First off, thanks for making and maintaining this software!  As a heads up, this is where I found your package: http://wagnerstechtalk.com/rg350tips/#RG-350_WiFi_Setup

I'm using an RG350M handheld but I have shell access via SSH.  I'm currently using opendingux built on May 21 2020.

When I attempt to run the .opk found on the main branch from the GMenu2X launcher I get a black screen with a cursor in the top left for a fraction of a second, then I crash and get dumped back to my launcher.  That was when I went to shell and found this error message:
```
opendingux:/media/data/apps # ./gcwconnect.opk
./gcwconnect.opk: line 3: syntax error: unexpected word (expecting ")")
```

Based on the other open issue thread, it seems there was a rewrite to support the Sept build of opendingux?  Is there a previous version of this that works for the May 21 2020 build?  If we expect the current version to work with the May build, I'm happy to help troubleshoot.

**Comment by hanskokx** [comment]
The .opk can't actually be launched directly from the command line in that way.  You'll need to put it in your apps directory and launch it from gmenu2x.  Alternatively, if you want to test it, you can grab the script and dependencies from the repo and run it via invoking python directly.

**Comment by jboulter11** [comment]
My bad, the dev branch opk still crashes when launching via gmenu2x though.

Sending the python script and data directory to my device reveals that I'm lacking the `urllib` dependency.  I am also lacking `pip` and apparently can't install `pip` without `zlib`.

I tried installing `urllib` from source code but it's also missing a dependency for `setuptools`.  `setuptools` also doesn't wanna install.  Is there a recommended way to resolve this?

Sorry if this is a dumb question, I'm an iOS dev by trade, so I don't really deal with this usually.  We compile then send to device. :P

**Comment by hanskokx** [comment]
I had to ask the devs to add the python packages I needed to the os. You 
might want to talk to the maintainers there.

**Comment by pcercuei** [comment]
The app is integrated in the 2021 builds of OpenDingux, by the way. Just update to the latest OD beta.

**Comment by hanskokx** [comment]
Paul to the rescue 😊

**Comment by jboulter11** [comment]
Unfortunately the OD beta doesn't seem to support my preferred launcher, SimpleMenu.  I really was hoping to keep everything else the same on my device.

Fortunately, though, it appears this commit works for my device.  It's presumably before your rewrite.

https://github.com/hanskokx/gcwconnect/blob/0b721bf746464c3e8b1065042172c27da5824ae7/gcwconnect.opk

So to anyone who finds their way here for their RG350 or RG350M, use that commit's `.opk` file for your stock firmware (May 21, 2020).

**Comment by pcercuei** [comment]
@jboulter11 I don't know the details as I don't use it myself, but people have been using SimpleMenu on OD beta for a while now.
